### ISSUE TITLE
[UI] "Exisiting template name" input supposed to be mandatory

### ISSUE THREAD

**Issue by dbeast-co** [dbeast-co/templates_generator#8]
In the "Project settings" page, the "Existing template name" input supposed to be mandatory.
The "Save" button supposed to be disabled til input is empty
Reproduce:
- Create new project 
- Fill required fields
- Mark "Add fields from existing template"
The "Save" button active, even if we doesn't fill the "Existing template name"

**Comment by devlev1980** [comment]
Done
